language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - main
deploy:
  provider: heroku
  api_key:
    secure: jnJ9+u6QX59oXQx6XWu1NQvVUWM5JsX19mDV3IOYw3dKvy9orhmxQCxAKZpJ6IpzzbhHBY4b71ddfLvueQvvTjd5X+He8+aObrQ2kdygiCCRn3gBGo9xgRp8WND7GU+PuVviKNTgz4xr8+xvWA18oUHSSDQhtSxt/ZfOZAjCWFaA0ilJO1dqPUO+jEdYazUAEYDl557FbkaUg/089svNjCdY83AA0JmJBCJzPUrTLN+KWE78Hy+chuGXCen4Gjp6/feeowovpYPqGimczpedSZGky4RvK2treRUNj7EuggpTzo3YqoQEVo8nBEPoWCsRglQRzwzXDM6yuboPLA4okKJkyBmuifUcki1YkEl8ZYj6mI5t5emfE4CN7w87FkXXc546zm+X45X/H25RxbLD96MtkwK6hNqL7flRYmIgsYiLmH+WaYtWLQva/bzSSZ97UI5Q0pjxceDV+B8v+YvOr3hfc9BCKKjbMuvPsxTt3UEaTLv7HKamLaE0vHzU9PLzRI4jTF1eCXmqFmpU11VE9MsWsu9HyNyZ2vMyd2fkN6+ey3awlHnM012WPXTQoc/6f0bjbHXEmI9T92v152tUtopybuz4f9MgfS7mjf9P8W0WSD0rQTgFBtjb16o/BjLmMOTS9xcWbDRX9bgDG+TnWP0fTKrjbQtTpCa4ST6YR0E=
  app: nent-a
  on:
    repo: aldinberi/nent
    branch: main
